import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import { colors } from "@/styles/colors";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeVars = {
    "--background": colors.background.DEFAULT,
    "--foreground": colors.primary.foreground,
    "--card": colors.background.secondary,
    "--card-foreground": colors.primary.foreground,
    "--popover": colors.background.secondary,
    "--popover-foreground": colors.primary.foreground,
    "--primary": colors.primary.DEFAULT,
    "--primary-foreground": colors.primary.foreground,
    "--secondary": colors.secondary.DEFAULT,
    "--secondary-foreground": colors.secondary.foreground,
    "--muted": colors.muted.DEFAULT,
    "--muted-foreground": colors.muted.foreground,
    "--accent": colors.accent.DEFAULT,
    "--accent-foreground": colors.accent.foreground,
    "--border": colors.border,
    "--input": colors.border,
    "--ring": colors.primary.DEFAULT,
  } as unknown as React.CSSProperties;

  return (
    <html lang="en" style={themeVars}>
      <body
        className={`${spaceGrotesk.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
